---
title: "A minimal flipbook"
subtitle: "With flipbookr and xaringan"
author: "Zahid Asghar"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
```

`r chunk_reveal("my_cars")`

```{r my_cars, include = FALSE}
cars %>%
  filter(speed > 4) %>%
  ggplot() +
  aes(x = speed) + #BREAK
  aes(y = dist) + #BREAK
  geom_point(
    alpha = .8, 
    color = "blue" 
    ) + 
  aes(size = speed) #BREAK
```

---

`r chunk_reveal("my_gapminder", break_type = "rotate", widths = c(1,1), title = "### cycle through lines of code marked #ROTATE")`


```{r my_gapminder, include=FALSE}
gapminder |> 
  filter(year == 2002) |> 
  select(-lifeExp) |> 
  rename(gdp_per_cap = gdpPercap) |> 
  mutate(gdp = gdp_per_cap * pop) |> 
  mutate(europe = continent == "Europe") |> 
  select(country, year, gdp, europe, pop)  |> 
  mutate(europe_category =
           case_when(europe == T ~ "Europe",
                     europe == F ~ "Not Europe")) |> 
  arrange(-gdp) |>  
    mutate(gdp_billions = gdp/1000000000) |> 
  slice(1:8) ->
  europe_or_not_2002
```




---

`r chunk_reveal("my_fill", break_type = "rotate", widths = c(1,1), title = "### cycle through lines of code marked #ROTATE")`

```{r my_fill, eval = F, echo = F}
ggplot(data = cars) +
  aes(x = speed) +
  aes(y = dist) +
  geom_point(size = 8,
             shape = 21,
             alpha = .9,
             color = "snow") +
  aes(fill = speed) +
  scale_fill_viridis_c(option = "magma") + #ROTATE
  scale_fill_viridis_c(option = "cividis") + #ROTATE
  scale_fill_viridis_c(option = "plasma") #ROTATE
```


---

`r chunk_reveal("cars_multi", break_type = 5, title = "### see multiple realizations of code")`

```{r cars_multi, include = FALSE}
cars %>% 
  sample_frac(size = 1, replace = TRUE) %>%      
  ggplot() +              
  aes(x = speed) +
  aes(y = dist) +
  geom_count(
    alpha = .7,
    color = "blue",
    size = 4
    ) + 
  geom_smooth(method = lm, se = FALSE) +
  coord_cartesian(xlim = range(cars$speed),
                  ylim = range(cars$dist)) +
  theme(legend.position = c(.9, .2))
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```



